"""
alert_manager.py -- Centralised Alert Storage and Export
=========================================================
This module is the "single source of truth" for all security alerts
generated by the AI Security Log Analyzer.  It collects alerts from
two independent detection systems:

    1. **ML model** (Isolation Forest) -- statistical anomaly detection
    2. **Rule engine** -- deterministic, threshold-based rules

Both types of alert are written into a single SQLite database so that
the dashboard (Step 5) and any future tooling can query them with
standard SQL.  An additional JSON export is produced for easy sharing
or integration with external systems (e.g. a SIEM or ticketing tool).

Output files:
    data/alerts.db    -- SQLite database with an "alerts" table
    data/alerts.json  -- JSON array of all alerts (human-readable)

Database schema (alerts table):
    id             INTEGER PRIMARY KEY   -- auto-incrementing row ID
    timestamp      TEXT                  -- when the suspicious event occurred
    alert_type     TEXT                  -- "ml" or "rule"
    severity       TEXT                  -- "low" / "medium" / "high" / "critical"
    affected_user  TEXT                  -- which user account was involved
    source_ip      TEXT                  -- the IP address under suspicion
    anomaly_score  REAL                  -- ML model's decision-function score
                                            (only meaningful for ML alerts;
                                             NULL for rule-based alerts)
    rule_name      TEXT                  -- which rule fired
                                            (NULL for ML alerts)
    description    TEXT                  -- human-readable explanation

Usage:
    python src/alert_manager.py          # standalone: runs detect + rules + store
    from src.alert_manager import ...    # import individual functions
"""

from __future__ import annotations

import json
import os
import sqlite3
from datetime import datetime

import joblib
import pandas as pd

# We import the rule engine so we can call it from our pipeline function.
# sys.path manipulation ensures the import works whether you run
# "python src/alert_manager.py" from the project root or
# "python alert_manager.py" from inside src/.
import sys
from pathlib import Path

# Add the src/ directory to Python's module search path so that
# "from rule_engine import ..." works regardless of the working directory.
_SRC_DIR = str(Path(__file__).resolve().parent)
if _SRC_DIR not in sys.path:
    sys.path.insert(0, _SRC_DIR)

from rule_engine import run_all_rules  # noqa: E402


# ---------------------------------------------------------------------------
# Constants -- file paths used throughout the module
# ---------------------------------------------------------------------------

# Where the feature-engineered login events live (input)
FEATURES_PATH = "data/processed/login_features.csv"

# Where the trained Isolation Forest model is stored (input)
MODEL_PATH = "models/isolation_forest.pkl"

# Where we write the SQLite database (output)
DB_PATH = "data/alerts.db"

# Where we write the JSON export (output)
JSON_PATH = "data/alerts.json"

# The same feature columns the model was trained on.
# IMPORTANT: this list must match the one in train_model.py exactly,
# otherwise the model will receive the wrong features and produce
# garbage predictions.
FEATURE_COLUMNS = [
    "hour",
    "day_of_week",
    "login_success",
    "is_night_login",
    "user_failed_count_total",
    "ip_failed_count_total",
    "is_new_ip_for_user",
    "is_new_device_for_user",
    "user_event_count",
]


# ---------------------------------------------------------------------------
# SQLite database setup
# ---------------------------------------------------------------------------

def init_db(db_path: str = DB_PATH) -> sqlite3.Connection:
    """Create (or open) the SQLite alerts database and ensure the table exists.

    If the database file does not exist yet, SQLite will create it
    automatically.  If the "alerts" table already exists, the
    CREATE TABLE IF NOT EXISTS statement is a safe no-op.

    Args:
        db_path: Filesystem path for the SQLite database file.

    Returns:
        An open sqlite3.Connection ready for inserts/queries.
    """
    # Make sure the parent directory exists (e.g. "data/")
    os.makedirs(os.path.dirname(db_path), exist_ok=True)

    # Connect to (or create) the database file
    conn = sqlite3.connect(db_path)

    # Create the alerts table if this is a fresh database.
    # Each column maps to one of the fields described in the module
    # docstring at the top of this file.
    conn.execute("""
        CREATE TABLE IF NOT EXISTS alerts (
            id             INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp      TEXT    NOT NULL,
            alert_type     TEXT    NOT NULL,
            severity       TEXT    NOT NULL,
            affected_user  TEXT,
            source_ip      TEXT,
            anomaly_score  REAL,
            rule_name      TEXT,
            description    TEXT
        )
    """)
    conn.commit()

    return conn


# ---------------------------------------------------------------------------
# Collecting ML-based alerts
# ---------------------------------------------------------------------------

def collect_ml_alerts(df: pd.DataFrame, model) -> list[dict]:
    """Run the Isolation Forest model and convert anomalies to alert dicts.

    The model assigns each event a prediction:
        -1 = anomaly  (suspicious)
         1 = normal   (benign)

    and a continuous anomaly_score (more negative = more anomalous).

    We filter for -1 predictions, then convert each anomalous row into
    a standardised alert dictionary that matches the database schema.

    Severity assignment for ML alerts:
        score <= -0.08  -->  "critical"   (very confident anomaly)
        score <= -0.05  -->  "high"
        score <= -0.02  -->  "medium"
        else            -->  "low"        (borderline anomaly)

    TODO: these severity thresholds are pretty arbitrary — should
    calibrate against labelled data properly at some point.

    Args:
        df:    The feature-engineered DataFrame (all events).
        model: A fitted sklearn IsolationForest model.

    Returns:
        A list of alert dicts, one per ML-detected anomaly.
    """
    # Ask the model to classify every event and score it
    predictions = model.predict(df[FEATURE_COLUMNS])
    scores = model.decision_function(df[FEATURE_COLUMNS])

    # Attach predictions back onto the DataFrame so we can filter
    df = df.copy()
    df["anomaly"] = predictions
    df["anomaly_score"] = scores

    # Keep only the rows the model flagged as anomalous (-1)
    anomalies = df[df["anomaly"] == -1]

    alerts: list[dict] = []
    for _, row in anomalies.iterrows():
        # Determine severity based on how extreme the anomaly score is.
        # More negative scores indicate stronger anomalies.
        score = row["anomaly_score"]
        if score <= -0.08:
            severity = "critical"
        elif score <= -0.05:
            severity = "high"
        elif score <= -0.02:
            severity = "medium"
        else:
            severity = "low"

        alerts.append({
            "timestamp": str(row["timestamp"]),
            "alert_type": "ml",
            "severity": severity,
            "affected_user": row["username"],
            "source_ip": row["source_ip"],
            "anomaly_score": round(float(score), 6),
            "rule_name": None,  # ML alerts don't come from a rule
            "description": (
                f"Isolation Forest flagged this event as anomalous "
                f"(score: {score:.4f}). "
                f"User: {row['username']}, IP: {row['source_ip']}, "
                f"Location: {row['location']}, Device: {row['device']}, "
                f"Login success: {row['login_success']}."
            ),
        })

    print(f"[Alert Manager] Collected {len(alerts)} ML-based alerts")
    return alerts


# ---------------------------------------------------------------------------
# Converting rule-engine alerts to the common schema
# ---------------------------------------------------------------------------

def collect_rule_alerts(rule_results: list[dict]) -> list[dict]:
    """Normalise rule-engine output into the common alert schema.

    The rule engine (rule_engine.py) returns dicts with keys like
    rule_name, severity, affected_user, source_ip, description,
    window_start, etc.  This function maps those into the same flat
    schema used by the database so both ML and rule alerts sit in one
    table.

    Args:
        rule_results: List of alert dicts from run_all_rules().

    Returns:
        A list of alert dicts matching the database schema.
    """
    alerts: list[dict] = []

    for rule_alert in rule_results:
        alerts.append({
            # Use the start of the detection window as the timestamp
            "timestamp": rule_alert.get("window_start", str(datetime.now())),
            "alert_type": "rule",
            "severity": rule_alert["severity"],
            "affected_user": rule_alert["affected_user"],
            "source_ip": rule_alert["source_ip"],
            "anomaly_score": None,  # Rule alerts don't have an ML score
            "rule_name": rule_alert["rule_name"],
            "description": rule_alert["description"],
        })

    print(f"[Alert Manager] Collected {len(alerts)} rule-based alerts")
    return alerts


# ---------------------------------------------------------------------------
# Writing alerts to SQLite
# ---------------------------------------------------------------------------

def store_alerts(conn: sqlite3.Connection, alerts: list[dict]) -> None:
    """Insert a batch of alerts into the SQLite database.

    Before inserting, we clear any existing rows so the table always
    reflects the latest pipeline run.  (If you want to keep historical
    runs, remove the DELETE statement and add a "run_id" column instead.)

    Args:
        conn:   An open sqlite3.Connection (from init_db).
        alerts: A list of alert dicts to insert.
    """
    cursor = conn.cursor()

    # HACK: wiping the table each run — should really add a run_id column
    # and keep history, but this works for now
    cursor.execute("DELETE FROM alerts")

    # Insert each alert as a new row.
    # We use a parameterised query (? placeholders) to prevent SQL
    # injection -- even though our data is internal, it's good practice.
    for alert in alerts:
        cursor.execute(
            """
            INSERT INTO alerts
                (timestamp, alert_type, severity, affected_user,
                 source_ip, anomaly_score, rule_name, description)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                alert["timestamp"],
                alert["alert_type"],
                alert["severity"],
                alert["affected_user"],
                alert["source_ip"],
                alert["anomaly_score"],
                alert["rule_name"],
                alert["description"],
            ),
        )

    conn.commit()
    print(f"[Alert Manager] Stored {len(alerts)} alerts in {DB_PATH}")


# ---------------------------------------------------------------------------
# Exporting alerts to JSON
# ---------------------------------------------------------------------------

def export_json(conn: sqlite3.Connection, json_path: str = JSON_PATH) -> None:
    """Export all alerts from the database to a JSON file.

    The JSON file is a simple array of objects, one per alert.  This
    format is easy to consume in JavaScript (for the dashboard), in
    other Python scripts, or in external tools like Splunk or Elastic.

    Args:
        conn:      An open sqlite3.Connection containing alerts.
        json_path: Output file path for the JSON export.
    """
    # row_factory = sqlite3.Row lets us access columns by name
    # instead of by numeric index, making the code more readable.
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM alerts ORDER BY id")

    # Convert each sqlite3.Row to a plain dict for JSON serialisation
    rows = [dict(row) for row in cursor.fetchall()]

    # Write with indent=2 for human readability.
    # ensure_ascii=False allows Unicode characters in descriptions.
    os.makedirs(os.path.dirname(json_path), exist_ok=True)
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(rows, f, indent=2, ensure_ascii=False)

    print(f"[Alert Manager] Exported {len(rows)} alerts to {json_path}")


# ---------------------------------------------------------------------------
# Full pipeline: detect + rules + store + export
# ---------------------------------------------------------------------------

def run_alert_pipeline() -> None:
    """Execute the complete alert-management pipeline.

    This is the main orchestrator that:
        1. Loads the feature-engineered event data
        2. Loads the trained Isolation Forest model
        3. Runs the ML model to find statistical anomalies
        4. Runs the rule engine to find deterministic violations
        5. Merges both sets of alerts
        6. Stores everything in SQLite
        7. Exports to JSON

    Call this function after train_model.py has finished.
    """
    print("=" * 55)
    print("  Security Log Analyzer -- Alert Manager")
    print("=" * 55)

    # ---- Step 1: Load inputs ----
    print("\n[1/5] Loading data and model ...")
    df = pd.read_csv(FEATURES_PATH)
    model = joblib.load(MODEL_PATH)
    print(f"       Loaded {len(df)} events from {FEATURES_PATH}")
    print(f"       Loaded model from {MODEL_PATH}")

    # ---- Step 2: Collect ML alerts ----
    print("\n[2/5] Running ML anomaly detection ...")
    ml_alerts = collect_ml_alerts(df, model)

    # ---- Step 3: Collect rule-based alerts ----
    print("\n[3/5] Running rule engine ...")
    rule_results = run_all_rules(df)
    rule_alerts = collect_rule_alerts(rule_results)

    # ---- Step 4: Merge and store in SQLite ----
    print("\n[4/5] Storing alerts in SQLite ...")
    all_alerts = ml_alerts + rule_alerts
    conn = init_db(DB_PATH)
    store_alerts(conn, all_alerts)

    # ---- Step 5: Export to JSON ----
    print("\n[5/5] Exporting alerts to JSON ...")
    export_json(conn, JSON_PATH)

    # ---- Done: print summary ----
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()

    # Count alerts by type for the summary
    cursor.execute(
        "SELECT alert_type, COUNT(*) as cnt FROM alerts GROUP BY alert_type"
    )
    type_counts = {row["alert_type"]: row["cnt"] for row in cursor.fetchall()}

    # Count alerts by severity for the summary
    cursor.execute(
        "SELECT severity, COUNT(*) as cnt FROM alerts GROUP BY severity"
    )
    severity_counts = {row["severity"]: row["cnt"] for row in cursor.fetchall()}

    conn.close()

    print("\n" + "=" * 55)
    print("  Alert Pipeline Complete -- Summary")
    print("=" * 55)
    print(f"  Total alerts stored  : {len(all_alerts)}")
    print(f"  ML-based alerts      : {type_counts.get('ml', 0)}")
    print(f"  Rule-based alerts    : {type_counts.get('rule', 0)}")
    print(f"  ---")
    # Print severity breakdown in order from most to least severe
    for sev in ["critical", "high", "medium", "low"]:
        count = severity_counts.get(sev, 0)
        if count > 0:
            print(f"  {sev.upper():<10}           : {count}")
    print(f"  ---")
    print(f"  SQLite database      : {DB_PATH}")
    print(f"  JSON export          : {JSON_PATH}")
    print("=" * 55)


# ---------------------------------------------------------------------------
# Standalone execution
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    run_alert_pipeline()
